// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ingrEZ.Data;

#nullable disable

namespace ingrEZ.Migrations
{
    [DbContext(typeof(IngrEZDataContext))]
    partial class IngrEZDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ingrEZ.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "difficulty");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "ingredients");

                    b.Property<string>("ItemizedInstructions")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "itemizedInstructions");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("varchar(9)")
                        .HasAnnotation("Relational:JsonPropertyName", "mealType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<DateTime?>("PinnedDate")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PreperationTime")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "preperationTime");

                    b.Property<int>("ServingSize")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "servingSize");

                    b.Property<string>("Suggestions")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "suggestions");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .HasDatabaseName("idx_hash");

                    b.ToTable("Recipe");
                });
#pragma warning restore 612, 618
        }
    }
}
